services:
  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    environment:
      - JAVA_OPTS=-Dotel.javaagent.enabled=false

  chromium-node:
    image: selenium/node-chromium:latest
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - JAVA_OPTS=-Dotel.javaagent.enabled=false
    volumes:
      - /dev/shm:/dev/shm

  cucumber-test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium-hub
    volumes:
      - .:/app
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-hub:4444/wd/hub
      - CUCUMBER_OPTIONS=--tags @smoke
